name: CI

on:
  push:
    branches: ["main"]
  workflow_call:
  pull_request:
    branches: ["main"]

env:
  MIX_ENV: test

permissions:
  contents: read

jobs:
  test:
    name: Build and test
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:15
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_DB: tandem
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.15.7'
        otp-version: '26.1.2'

    - name: Restore dependencies cache
      uses: actions/cache@v4
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-

    - name: Install dependencies
      run: mix deps.get

    - name: Compile dependencies
      run: mix deps.compile

    - name: Check Formatting
      run: mix format --check-formatted

    - name: Check Credo
      run: mix credo --strict

    - name: Check Unused Dependencies
      run: mix deps.unlock --check-unused

    - name: Compile
      run: mix compile --warnings-as-errors

    - name: Create Database Schema
      run: psql -h localhost -U postgres -d tandem -c "CREATE SCHEMA IF NOT EXISTS crawl"

    - name: Run tests
      run: mix test
